### ISSUE TITLE
PokeDex flagging for bulk storage transfer isn't working.

### ISSUE THREAD

**Issue by DavidG777** [BernardoGiordano/PKSM#569] opened 2017-11-21 08:38 UTC
When using the button to quickly transfer an entire box from storage to the save file, none of the Pokemon are flagged in the Pokedex. Moving them one by one works fine, but bulk doesn't.

I'm using PKSM 5.0.1 with Ultra Moon.

**Comment by RinMaru** [comment] 2017-11-21 15:51
same issue here

**Comment by AgeSlacker** [comment] 2017-11-21 21:56
Same problem on Ultra Moon and Ultra Sun.

**Comment by tardisx** [comment] 2017-11-21 22:47
Confirmed that moving a single Pokémon to storage and back again, populates the Dex, the bulk transfer does not.

**Comment by ewormPL** [comment] 2017-11-24 19:30
Quick filling of the dex on a new game is best handled with this bulk transfer. The fact that the Pokdéex doesn't react to the Pokémon is a problem. I really hope it's fixed in the next version.

Also, while we're on topic, it would be convenient if there was a button option for the bulk transfer, not just a touch screen one. Maybe Y?

**Comment by BernardoGiordano** [comment] 2017-11-24 21:22
the bug should now be fixed, please compile from latest commit yourself and test changes to see if you can still reproduce the bug.

**Comment by ewormPL** [comment] 2017-11-25 17:27
Compiled and... now I can't open my saves in PKSM at all. "Incorrect size for this game". What?

**Comment by BernardoGiordano** [comment] 2017-11-25 17:28
you didn't compile it correctly, then

**Comment by ewormPL** [comment] 2017-11-25 17:30
How do I compile correctly then? It didn't show me no error...

**Comment by BernardoGiordano** [comment] 2017-11-25 17:34
First of all, for which platform did you use it? Homebrew, rosalina or cia?

**Comment by ewormPL** [comment] 2017-11-25 17:37
I use Rosalina.
Maybe I should mention that at first I got a "no such file or directory" error for memecrypto.h, but I downloaded the source/memecrypto folder separately (the files were missing from the PKSM-master zip), cleaned the project and it compiled fine then.

**Comment by BernardoGiordano** [comment] 2017-11-25 17:40
you should have cloned recursively, because memecrypto is a submodule. Anyways, you need to set the `ROSALINA` flag in the makefile to `1` if compiling for rosalina. That's why your error

**Comment by ewormPL** [comment] 2017-11-25 17:49
You mean edit the file itself? Where is the flag? I'm not exactly a pro here, sorry...

**Comment by ewormPL** [comment] 2017-11-25 17:54
Nevermind, figured it out.

**Comment by ewormPL** [comment] 2017-11-25 18:06
And yes, the dex problem is indeed solved. Great job!

**Closed** 2017-11-25 18:20 UTC

**Comment by Pokefanmati** [comment] 2019-01-02 00:52
Aparently is back, I'm in 6.0.0 and I'm having it with Pokémon Black 2
