### ISSUE TITLE
Mega Evolution Symbol

### ISSUE THREAD

**Issue by Krenk0** [BernardoGiordano/PKSM#113] opened 2017-01-01 00:58 UTC
Hi!

I made some changes on some pokemons (made them shiny and stuff like that) and, when I used them ingame, they had the mega evolution simbol next to the HP bar. Don't know why and if it is a bug.

Sorry for my english btw.

**Comment by kwsch** [comment] 2017-01-01 01:22
This is usually indicative of corrupted party stat values (ie, all the bytes after 232/0xE8), as status bitflags/counters are used for battle to keep track of things like Mega Evolution status.

Depositing and withdrawing them from the PC should reset the values ingame.

**Comment by Krenk0** [comment] 2017-01-01 01:33
Thank you :+1:

**Comment by BernardoGiordano** [comment] 2017-01-17 19:14
this refers to an older version, newer ones have this feature unlocked until the problem is solved. Closing

**Closed by BernardoGiordano** 2017-01-17 19:14 UTC
