### ISSUE TITLE
Pokedex entry no updated when transfer a complete box

### ISSUE THREAD

**Issue by XiNaru** [BernardoGiordano/PKSM#512] opened 2017-10-10 09:28 UTC

**Comment by BernardoGiordano** [comment] 2017-10-10 09:30
Duplicate of #511

**Closed by BernardoGiordano** 2017-10-10 09:30 UTC

**Comment by XiNaru** [comment] 2017-10-10 10:05
no it is NOT a duplicate. i speak not from gen 6. i speak from gen7 oder al
other

2017-10-10 11:30 GMT+02:00 Bernardo Giordano <notifications@github.com>:
