### ISSUE TITLE
Ability to rename the Extra Storage boxes

### ISSUE THREAD

**Issue by GriffinG1** [BernardoGiordano/PKSM#403] opened 2017-06-05 07:33 UTC
Recently moved my living dex from pokebank to there and being able to rename those boxes would make it a hell of a lot easier to find pokemon. Doubt I'm the only person with a living dex there too.

**Comment by BernardoGiordano** [comment] 2017-07-17 11:50
Closing since duplicate of #170

**Closed by BernardoGiordano** 2017-07-17 11:50 UTC
