### ISSUE TITLE
Eon Ticket does not work

### ISSUE THREAD

**Issue by Sturmrufer** [BernardoGiordano/PKSM#12] opened 2016-09-07 02:01 UTC
Once injected and received, the eon ticket does not function correctly, as in at all. Perhaps there is a way around this?

**Comment by BernardoGiordano** [comment] 2016-09-07 07:53
This is not related to the wondercard, there's an eventflag somewhere to be removed.

**Comment by Sturmrufer** [comment] 2016-09-09 01:29
That seems to be incorrect. I obtained an alternate wc6 and it worked like a charm. Uploaded below



[ORAS - Eon Ticket.zip](https://github.com/BernardoGiordano/EventAssistant/files/463013/ORAS.-.Eon.Ticket.zip)

**Comment by kwsch** [comment] 2016-09-09 03:42
```
            if (g is WC6)
            {
                if (g.CardID == 2048 && g.Item == 726) // Eon Ticket (OR/AS)
                {
                    if (!Main.SAV.ORAS || ((SAV6)SAV).EonTicket < 0)
                        goto reject;
                    BitConverter.GetBytes(WC6.EonTicketConst).CopyTo(SAV.Data, ((SAV6)SAV).EonTicket);
                }
            }
```

Basically, write 0x225D73C2 to 0x319B8 if the cardID is 0x800 and the given item is 726 (just to be sure). The games have some anti-cheat in that if you receive 726 via gift, it'll permanently disable the event (with event flags); if you have the value it will unlock it (enable the NPC events).

The value writing is done probably when the game boots (maybe checks streetpass data when it starts up to see if it gets this event wc6).

**Comment by BernardoGiordano** [comment] 2016-09-09 14:52
Thanks to Kaphotics the issue is (hopefully) fixed. [Changes are here](https://github.com/BernardoGiordano/EventAssistant/commit/c409b822205a04609669dba14f244621ccc71aa7), @Sturmrufer please let me know if injection works with [this build](https://github.com/BernardoGiordano/EventAssistant/blob/master/EventAssistant/EventAssistant.cia?raw=true)

**Comment by Sturmrufer** [comment] 2016-09-10 00:20
Sadly, it seems to not work. I used the 3dsx file, since I only have HB for now, and still no dice.

**Comment by kwsch** [comment] 2016-09-10 02:19
You'd have to restore your save file from before the edit. If you receive the Eon Ticket item via the deliveryman and don't have the Eon Ticket Constant set, the game will permanently lock you out of the event by flagging the event as completed.

**Comment by Sturmrufer** [comment] 2016-09-10 03:00
Whatever do you mean? This was tested upon a save file that had not been edited at all. And anyways, when I used PkHeX to remove the ticket inject by this and injected the wondercard I supplied, and it worked perfectly.

**Comment by BernardoGiordano** [comment] 2016-09-10 07:16
Tried personally to inject that wondercard, everything works fine now. Closing

**Comment by BernardoGiordano** [comment] 2016-09-10 07:28
Reopening, because it seems to work only once more .-.

**Closed** 2016-11-20 20:37 UTC

**Comment by br1980** [comment] 2017-02-02 20:48
I get an error when trying to inject the Eon Ticket card.  Today's my first day messing with save editors so I definitely haven't had the flag set before.
