### ISSUE TITLE
Bulbasaur Bug still existing

### ISSUE THREAD

**Issue by pattax** [BernardoGiordano/PKSM#152] opened 2017-01-09 22:39 UTC
Edited my Event Munchlax a little. Made it shiny and edited it's level from 26 to 27.
Yes I used the 4.0.1 Update!

**Comment by udelgadochio** [comment] 2017-01-11 00:18
Is there anyway to return them to normal? I have the same problem!! :(

**Comment by BernardoGiordano** [comment] 2017-01-11 06:27
Do not edit them in your party. Restore one of the automatic backups if you want it back normal

**Comment by pattax** [comment] 2017-01-11 19:24
You can either load a backup or save them in PKHex to normal.

**Comment by BernardoGiordano** [comment] 2017-01-17 19:12
this refers to an older version, newer ones have this feature unlocked until the problem is solved. Closing

**Closed by BernardoGiordano** 2017-01-17 19:12 UTC
