### ISSUE TITLE
Alolan versions problems

### ISSUE THREAD

**Issue by Zorua707** [BernardoGiordano/PKSM#122] opened 2017-01-01 20:46 UTC
Hello, I had some problems with some alolan versions, Alolan Raichu and Alolan Ninetales.
I finished editing them and then opened the game normally, and used them in battle. Then after I saved the game, they appeared in their normal versions. Could you know why this is happening? Thank you! (Sorry for bad grammar). 
EDIT: I didn't notice at first, but their screams are also altered, Alolan Ninetales has Greninja's and I couldn't really know wich one Alolan Raichu had.

**Comment by downspath** [comment] 2017-01-01 21:59
did you edit them while they where in your team? pokemons in your team are buggy if you change them even with pkhex,

**Comment by Zorua707** [comment] 2017-01-01 22:08
Oh, thanks for telling me! Now that you say it yes, they were on my team. I edited some new ones some minutes ago, while they were in the box. They won't change again, right...?

**Comment by downspath** [comment] 2017-01-01 22:18
I don`t know, i always edit the Pokemon in the boxes, because i always hear people have problems with them after editing them in the team.

**Comment by Zorua707** [comment] 2017-01-01 22:21
Ok, i won't edit them in the team anymore, thanks a lot!!

**Comment by BernardoGiordano** [comment] 2017-01-17 19:13
this refers to an older version, newer ones have this feature unlocked until the problem is solved. Closing

**Closed by BernardoGiordano** 2017-01-17 19:13 UTC
